branch: 'main'
repoUrl: 'https://github.com/oneaboveallms/nginx.ms.git'
approvalMessage: 'Do you want to proceed with Ansible Playbook execution?'
approvalButton: 'Proceed'
playbookPath: 'install.yml'
inventory_file: 'inventory.ini'
slackChannel: 'all-oneaboveall'
successMessage: 'Pipeline Job Succeeded'
failureMessage: 'Pipeline Job Failed'
unstableMessage: 'Pipeline Job is Unstable'
