branch: 'main'
repoUrl: 'https://github.com/oneaboveallms/zabbix.ms.git'
approvalMessage: 'Do you want to proceed with Ansible Playbook execution?'
approvalButton: 'Proceed'
playbookPath: 'install.yaml'
slackChannel: 'all-oneaboveall'
successMessage: 'Pipeline Job Succeeded'
failureMessage: 'Pipeline Job Failed'
unstableMessage: 'Pipeline Job is Unstable'
